pub mod navbar;
pub mod footer;
pub mod header;
// pub mod hello;
// pub mod class;
// pub mod message;
// pub mod counter;
// pub mod function_click;
// pub mod class_click;
// pub mod event_bind;
// pub mod parent_component;
// pub mod child_component;
// pub mod nested_child_with_props;
// pub mod inner_html;
// pub mod user_greeting;
// pub mod name_list; 
// pub mod person;
// pub mod stylesheets;
// pub mod form_input;
// pub mod form_area;
pub mod lifecycleA;